### ISSUE TITLE
To be able to change the next, done and skip button colors ?

### ISSUE THREAD

**Issue by B-e-r-k-e-r** [imRahulChouhan/introduction_slider#2]
Hi mate, thanks for this awesome package, is it possible to change the colors of the buttons ? Or if I create my own widget for next, a callback to the next button function ? Also I would love to be able to set a gradient color for the backgroundColor which I couldn't. 

Also a small bug, if I define my own done widget (TextButton(child: Text('Let's go'), on the last page where done appears, dotIndicator changes position.

**Comment by chouhan-rahul** [comment]
Thank you for the report. I'll fix this issue ASAP.
